### ISSUE TITLE
Argmax unexpected key and Cant convert Cuda tensor to Numpy error

### ISSUE THREAD

**Issue by rishabhjoshi** [kaushaltrivedi/fast-bert#152]
Hi I am facing the issue below. I have installed fast-bert using pip and just copied the code from the readme.
Any suggestions on how to fix?

```
model/tensorboard
Traceback (most recent call last):
  File "/usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
TypeError: argmax() got an unexpected keyword argument 'axis'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_bert.py", line 67, in <module>
    main()
  File "train_bert.py", line 62, in main
    optimizer_type="lamb")
  File "/usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/fast_bert/learner_cls.py", line 406, in fit
    results = self.validate()
  File "/usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/fast_bert/learner_cls.py", line 524, in validate
    all_logits, all_labels
  File "/usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/fast_bert/metrics.py", line 15, in accuracy
    outputs = np.argmax(y_pred, axis=1)
  File "<__array_function__ internals>", line 6, in argmax
  File "/usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1153, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 70, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "/usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/usr1/home/rjoshi2/envs/myenv/lib/python3.7/site-packages/torch/tensor.py", line 433, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

```

**Comment by rishabhjoshi** [comment]
I even tried to install fast-bert using github. Same error.

**Comment by rishabhjoshi** [comment]
Also, this error comes after 1 epoch is done and for train and validation.

**Comment by josh-cooper** [comment]
This occurs with the new version released today. Try pip installling version 1.5.0.

**Comment by kaushaltrivedi** [comment]
should be fixed in v1.5.2.  please check.

**Comment by rishabhjoshi** [comment]
Tried v1.5.2 also. Same problem.

**Comment by rishabhjoshi** [comment]
@josh-cooper 's answer (v1.5.0) fixed it!

**Comment by William8Work** [comment]
will this be fixed in the new version? I tried 1.6.0, same problem.

**Comment by talhaanwarch** [comment]
facing same issue in lastest version, i belived its 1.60 , i am using google colab

**Comment by manishiitg** [comment]
still getting the same issue for me as well 
can't convert CUDA tensor to numpy.
